Migrate diagrammatic equations
AlgebraicJulia/Decapodes.jl pull request #183
Opened 2024-01-09 17:05 UTC by quffaro

2024-01-09 17:06 UTC, lukem12345 commented on Project.toml
> +DiagrammaticEquations = "6f00c28b-6bed-4403-80fa-30e0dc12f317"
There should be a [compat] entry for DiagrammaticEquations

2024-01-09 17:08 UTC, lukem12345 commented on examples/chemistry/brusselator_bounded.jl
> +u₀ = construct(PhysicsState,
This should be updated to use the `ComponentArray` constructor as in the other examples.

2024-01-09 17:09 UTC, lukem12345 commented on src/Decapodes.jl
>  append_dot(s::Symbol) = Symbol(string(s)*'\U0307')
Is this meant to stay here?

2024-01-09 17:09 UTC, lukem12345 commented on src/simulation.jl
> +# TODO: Matt - Delete
Delete

2024-01-09 17:11 UTC, lukem12345 commented on test/simulation.jl
> +# , infer_states, infer_state_names
Delete this if not necessary.

2024-01-10 17:51 UTC, lukem12345 commented
You can fix the failing Docs build (aside from the random 404 error) by setting the `docs/Project.toml` compat entry for CairoMakie to 0.10

2024-01-10 23:28 UTC, jpfairbanks commented
@lukem12345 @quffaro @olynch, can we make a full court press on this so that it doesn't start holding up changes to main?

2024-01-12 15:13 UTC, lukem12345 requested changes

2024-01-12 15:13 UTC, lukem12345 commented on test/composition.jl
@quffaro I don’t think this file is called by runtests in this branch’s current state. Is this meant to be in DgmEqns?

2024-01-12 15:50 UTC, quffaro commented on test/composition.jl
Yup you're right. I've just re-tested with test/composition moved over to DiagrammaticEquations. I'll push onto DE#main and the re-commit to this PR.

2024-01-12 15:53 UTC, lukem12345 commented on test/composition.jl
Ok. If tests pass here and docs build correctly, then this is ready to approve upon the next review request

2024-01-12 17:38 UTC, lukem12345 approved these changes

2024-01-12 17:47 UTC, merged